/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Catalog Items
 * Use the Selling Partner API for Catalog Items to retrieve information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-04-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Classification (browse node) for an Amazon catalog item.
 * @export
 * @interface ItemBrowseClassification
 */
export interface ItemBrowseClassification {
    /**
     * Display name for the classification.
     * @type {string}
     * @memberof ItemBrowseClassification
     */
    'displayName': string;
    /**
     * Identifier of the classification.
     * @type {string}
     * @memberof ItemBrowseClassification
     */
    'classificationId': string;
    /**
     * 
     * @type {ItemBrowseClassification}
     * @memberof ItemBrowseClassification
     */
    'parent'?: ItemBrowseClassification;
}

