/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Direct Fulfillment Orders
 * The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor\'s order data.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Status of acknowledgement.
 * @export
 * @interface AcknowledgementStatus
 */
export interface AcknowledgementStatus {
    /**
     * Acknowledgement code is a unique two digit value which indicates the status of the acknowledgement. For a list of acknowledgement codes that Amazon supports, see the Vendor Direct Fulfillment APIs Use Case Guide.
     * @type {string}
     * @memberof AcknowledgementStatus
     */
    'code'?: string;
    /**
     * Reason for the acknowledgement code.
     * @type {string}
     * @memberof AcknowledgementStatus
     */
    'description'?: string;
}

