/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Direct Fulfillment Orders
 * The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor\'s order data.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Gift details for the item.
 * @export
 * @interface GiftDetails
 */
export interface GiftDetails {
    /**
     * Gift message to be printed in shipment.
     * @type {string}
     * @memberof GiftDetails
     */
    'giftMessage'?: string;
    /**
     * Gift wrap identifier for the gift wrapping, if any.
     * @type {string}
     * @memberof GiftDetails
     */
    'giftWrapId'?: string;
}

