/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Replenishment
 * The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.
 *
 * The version of the OpenAPI document: 2022-11-07
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TimeInterval } from './time-interval';

/**
 * An object which contains offer metrics.
 */
export interface ListOfferMetricsResponseOffer {
    /**
     * The Amazon Standard Identification Number (ASIN).
     */
    'asin'?: string;
    /**
     * The percentage of items that were not shipped out of the total shipped units over a period of time due to being out of stock. Applicable to PERFORMANCE timePeriodType.
     */
    'notDeliveredDueToOOS'?: number;
    /**
     * The revenue generated from subscriptions over a period of time. Applicable to PERFORMANCE timePeriodType.
     */
    'totalSubscriptionsRevenue'?: number;
    /**
     * The number of units shipped to the subscribers over a period of time. Applicable to PERFORMANCE timePeriodType.
     */
    'shippedSubscriptionUnits'?: number;
    /**
     * The number of active subscriptions present at the end of the period. Applicable to PERFORMANCE timePeriodType.
     */
    'activeSubscriptions'?: number;
    /**
     * The percentage of total program revenue out of total product revenue. Applicable to PERFORMANCE timePeriodType.
     */
    'revenuePenetration'?: number;
    /**
     * The revenue that would have been generated had there not been out of stock. Applicable to PERFORMANCE timePeriodType.
     */
    'lostRevenueDueToOOS'?: number;
    /**
     * The percentage of revenue from ASINs with coupons out of total revenue from all ASINs. Applicable to PERFORMANCE timePeriodType.
     */
    'couponsRevenuePenetration'?: number;
    /**
     * The percentage of new subscriptions acquired through coupons. Applicable to PERFORMANCE timePeriodType.
     */
    'shareOfCouponSubscriptions'?: number;
    /**
     * The forecasted total subscription revenue for the next 30 days. Applicable to FORECAST timePeriodType.
     */
    'next30DayTotalSubscriptionsRevenue'?: number;
    /**
     * The forecasted total subscription revenue for the next 60 days. Applicable to FORECAST timePeriodType.
     */
    'next60DayTotalSubscriptionsRevenue'?: number;
    /**
     * The forecasted total subscription revenue for the next 90 days. Applicable to FORECAST timePeriodType.
     */
    'next90DayTotalSubscriptionsRevenue'?: number;
    /**
     * The forecasted shipped subscription units for the next 30 days. Applicable to FORECAST timePeriodType.
     */
    'next30DayShippedSubscriptionUnits'?: number;
    /**
     * The forecasted shipped subscription units for the next 60 days. Applicable to FORECAST timePeriodType.
     */
    'next60DayShippedSubscriptionUnits'?: number;
    /**
     * The forecasted shipped subscription units for the next 90 days. Applicable to FORECAST timePeriodType.
     */
    'next90DayShippedSubscriptionUnits'?: number;
    'timeInterval'?: TimeInterval;
    /**
     * The currency code in ISO 4217 format.
     */
    'currencyCode'?: string;
}

