/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for Orders
 * The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Tax invoicing information for the order.
 */
export interface OrderTaxInvoicing {
    /**
     * The buyer\'s invoicing preference, which indicates whether the seller should issue an individual or a business invoice to the buyer.    **Note**: This attribute is only available in the Turkey marketplace.   **Possible values**: - `INDIVIDUAL` (Issues an individual invoice to the buyer) - `BUSINESS` (Issues a business invoice to the buyer)
     */
    'buyerInvoicePreference'?: string;
    /**
     * The status of the invoice. Only available for Easy Ship orders and orders in the Brazil marketplace.  **Possible values**: - `NOT_REQUIRED` (The order does not require an electronic invoice to be uploaded) - `NOT_FOUND` (The order requires an electronic invoice but it is not uploaded) - `PROCESSING` (The required electronic invoice was uploaded and is processing) - `ERRORED` (The uploaded electronic invoice was not accepted) - `ACCEPTED` (The uploaded electronic invoice was accepted)
     */
    'invoiceStatus'?: string;
}

