version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    versioning-strategy: increase
    schedule:
      interval: weekly
    groups:
      jest:
        patterns:
          - "@jest/types"
          - "@swc/core"
          - "@swc/jest"
          - "@types/jest"
          - "jest"
      lerna-lite:
        patterns:
          - "@lerna-lite/*"
