/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Retail Procurement Orders
 * The Selling Partner API for Retail Procurement Orders provides programmatic access to vendor orders data.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Details of quantity ordered.
 */
export interface ItemQuantity {
    /**
     * Acknowledged quantity. This value should not be zero.
     */
    'amount'?: number;
    /**
     * Unit of measure for the acknowledged quantity.
     */
    'unitOfMeasure'?: ItemQuantityUnitOfMeasureEnum;
    /**
     * The case size, in the event that we ordered using cases.
     */
    'unitSize'?: number;
}

export const ItemQuantityUnitOfMeasureEnum = {
    Cases: 'Cases',
    Eaches: 'Eaches'
} as const;

export type ItemQuantityUnitOfMeasureEnum = typeof ItemQuantityUnitOfMeasureEnum[keyof typeof ItemQuantityUnitOfMeasureEnum];


