/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Retail Procurement Orders
 * The Selling Partner API for Retail Procurement Orders provides programmatic access to vendor orders data.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AcknowledgementStatusDetails } from './acknowledgement-status-details';
// May contain unused imports in some cases
// @ts-ignore
import type { ItemQuantity } from './item-quantity';

/**
 * Acknowledgement status information.
 */
export interface OrderItemStatusAcknowledgementStatus {
    /**
     * Confirmation status of line item.
     */
    'confirmationStatus'?: OrderItemStatusAcknowledgementStatusConfirmationStatusEnum;
    'acceptedQuantity'?: ItemQuantity;
    'rejectedQuantity'?: ItemQuantity;
    /**
     * Details of item quantity confirmed.
     */
    'acknowledgementStatusDetails'?: Array<AcknowledgementStatusDetails>;
}

export const OrderItemStatusAcknowledgementStatusConfirmationStatusEnum = {
    Accepted: 'ACCEPTED',
    PartiallyAccepted: 'PARTIALLY_ACCEPTED',
    Rejected: 'REJECTED',
    Unconfirmed: 'UNCONFIRMED'
} as const;

export type OrderItemStatusAcknowledgementStatusConfirmationStatusEnum = typeof OrderItemStatusAcknowledgementStatusConfirmationStatusEnum[keyof typeof OrderItemStatusAcknowledgementStatusConfirmationStatusEnum];


