/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for Sellers
 * The [Selling Partner API for Sellers](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference) (Sellers API) provides essential information about seller accounts, such as:  - The marketplaces a seller can list in - The default language and currency of a marketplace - Whether the seller has suspended listings  Refer to the [Sellers API reference](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference) for details about this API\'s operations, data types, and schemas.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Business } from './business';
// May contain unused imports in some cases
// @ts-ignore
import type { MarketplaceParticipation } from './marketplace-participation';
// May contain unused imports in some cases
// @ts-ignore
import type { PrimaryContact } from './primary-contact';

/**
 * The response schema for the `getAccount` operation.
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * List of marketplace participations.
     * @type {Array<MarketplaceParticipation>}
     * @memberof Account
     */
    'marketplaceParticipationList': Array<MarketplaceParticipation>;
    /**
     * The type of business registered for the seller account.
     * @type {string}
     * @memberof Account
     */
    'businessType': AccountBusinessTypeEnum;
    /**
     * The selling plan details.
     * @type {string}
     * @memberof Account
     */
    'sellingPlan': AccountSellingPlanEnum;
    /**
     * 
     * @type {Business}
     * @memberof Account
     */
    'business'?: Business;
    /**
     * 
     * @type {PrimaryContact}
     * @memberof Account
     */
    'primaryContact'?: PrimaryContact;
}

export const AccountBusinessTypeEnum = {
    Charity: 'CHARITY',
    Craftsman: 'CRAFTSMAN',
    NaturalPersonCompany: 'NATURAL_PERSON_COMPANY',
    PublicListed: 'PUBLIC_LISTED',
    PrivateLimited: 'PRIVATE_LIMITED',
    SoleProprietorship: 'SOLE_PROPRIETORSHIP',
    StateOwned: 'STATE_OWNED',
    Individual: 'INDIVIDUAL'
} as const;

export type AccountBusinessTypeEnum = typeof AccountBusinessTypeEnum[keyof typeof AccountBusinessTypeEnum];
export const AccountSellingPlanEnum = {
    Professional: 'PROFESSIONAL',
    Individual: 'INDIVIDUAL'
} as const;

export type AccountSellingPlanEnum = typeof AccountSellingPlanEnum[keyof typeof AccountSellingPlanEnum];


