/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for Support
 * The Selling Partner API for Support provides programmatic access to information about Selling Partner support.
 *
 * The version of the OpenAPI document: 2025-02-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Attachment } from './attachment.js';
// May contain unused imports in some cases
// @ts-ignore
import type { Participant } from './participant.js';

/**
 * The content of an email contact.
 */
export interface EmailContent {
    'sender': Participant;
    /**
     * The email body of the contact.
     */
    'message': string;
    /**
     * All attachments included in the contact.
     */
    'attachments'?: Array<Attachment>;
}

