/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon\'s fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * The version of the OpenAPI document: 2020-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A physical address.
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * The name of the person, business or institution at the address.
     * @type {string}
     * @memberof Address
     */
    'name': string;
    /**
     * The first line of the address.
     * @type {string}
     * @memberof Address
     */
    'addressLine1': string;
    /**
     * Additional address information, if required.
     * @type {string}
     * @memberof Address
     */
    'addressLine2'?: string;
    /**
     * Additional address information, if required.
     * @type {string}
     * @memberof Address
     */
    'addressLine3'?: string;
    /**
     * The city where the person, business, or institution is located.
     * @type {string}
     * @memberof Address
     */
    'city'?: string;
    /**
     * The district or county where the person, business, or institution is located.
     * @type {string}
     * @memberof Address
     */
    'districtOrCounty'?: string;
    /**
     * The state or region where the person, business or institution is located.
     * @type {string}
     * @memberof Address
     */
    'stateOrRegion': string;
    /**
     * The postal code of the address.
     * @type {string}
     * @memberof Address
     */
    'postalCode'?: string;
    /**
     * The two digit country code. In ISO 3166-1 alpha-2 format.
     * @type {string}
     * @memberof Address
     */
    'countryCode': string;
    /**
     * The phone number of the person, business, or institution located at the address.
     * @type {string}
     * @memberof Address
     */
    'phone'?: string;
}

