/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon\'s fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * The version of the OpenAPI document: 2020-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A physical address.
 */
export interface Address {
    /**
     * The name of the person, business or institution at the address.
     */
    'name': string;
    /**
     * The first line of the address.
     */
    'addressLine1': string;
    /**
     * Additional address information, if required.
     */
    'addressLine2'?: string;
    /**
     * Additional address information, if required.
     */
    'addressLine3'?: string;
    /**
     * The city where the person, business, or institution is located. This property is required in all countries except Japan. It should not be used in Japan.
     */
    'city'?: string;
    /**
     * The district or county where the person, business, or institution is located.
     */
    'districtOrCounty'?: string;
    /**
     * The state or region where the person, business or institution is located.
     */
    'stateOrRegion'?: string;
    /**
     * The postal code of the address.
     */
    'postalCode': string;
    /**
     * The two digit country code. In ISO 3166-1 alpha-2 format.
     */
    'countryCode': string;
    /**
     * The phone number of the person, business, or institution located at the address.
     */
    'phone'?: string;
}

