/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon\'s fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * The version of the OpenAPI document: 2020-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The event code for the delivery event.
 * @export
 * @enum {string}
 */

export const EventCode = {
    _101: 'EVENT_101',
    _102: 'EVENT_102',
    _201: 'EVENT_201',
    _202: 'EVENT_202',
    _203: 'EVENT_203',
    _204: 'EVENT_204',
    _205: 'EVENT_205',
    _206: 'EVENT_206',
    _301: 'EVENT_301',
    _302: 'EVENT_302',
    _304: 'EVENT_304',
    _306: 'EVENT_306',
    _307: 'EVENT_307',
    _308: 'EVENT_308',
    _309: 'EVENT_309',
    _401: 'EVENT_401',
    _402: 'EVENT_402',
    _403: 'EVENT_403',
    _404: 'EVENT_404',
    _405: 'EVENT_405',
    _406: 'EVENT_406',
    _407: 'EVENT_407',
    _408: 'EVENT_408',
    _409: 'EVENT_409',
    _411: 'EVENT_411',
    _412: 'EVENT_412',
    _413: 'EVENT_413',
    _414: 'EVENT_414',
    _415: 'EVENT_415',
    _416: 'EVENT_416',
    _417: 'EVENT_417',
    _418: 'EVENT_418',
    _419: 'EVENT_419'
} as const;

export type EventCode = typeof EventCode[keyof typeof EventCode];



