/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon\'s fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * The version of the OpenAPI document: 2020-07-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FulfillmentPreviewItem } from './fulfillment-preview-item';

/**
 * Delivery and item information for a shipment in a fulfillment order preview.
 * @export
 * @interface FulfillmentPreviewShipment
 */
export interface FulfillmentPreviewShipment {
    /**
     * 
     * @type {string}
     * @memberof FulfillmentPreviewShipment
     */
    'earliestShipDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentPreviewShipment
     */
    'latestShipDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentPreviewShipment
     */
    'earliestArrivalDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentPreviewShipment
     */
    'latestArrivalDate'?: string;
    /**
     * Provides additional insight into the shipment timeline when exact delivery dates are not able to be precomputed.
     * @type {Array<string>}
     * @memberof FulfillmentPreviewShipment
     */
    'shippingNotes'?: Array<string>;
    /**
     * An array of fulfillment preview item information.
     * @type {Array<FulfillmentPreviewItem>}
     * @memberof FulfillmentPreviewShipment
     */
    'fulfillmentPreviewItems': Array<FulfillmentPreviewItem>;
}

