/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for Amazon External Fulfillment Shipments Processing
 * You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon\'s external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.
 *
 * The version of the OpenAPI document: 2024-09-11
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LineItemWithReason } from './line-item-with-reason';

/**
 * Information about the shipment and its line items, used to confirm or reject line items.
 */
export interface ShipmentAcknowledgementRequest {
    /**
     * A unique identifier for every shipment rejection.
     */
    'referenceId'?: string;
    /**
     * Details about the line items from the shipment that are being confirmed or rejected by the seller.
     */
    'lineItems': Array<LineItemWithReason>;
}

