version: 2.1

defaults:
  workspace_root: &workspace_root
    ~/selling-partner-api-sdk

  nodejs_container: &nodejs_container
    working_directory: *workspace_root
    docker:
      - image: cimg/node:lts

  test_container: &test_container
    working_directory: *workspace_root
    docker:
      - image: cimg/node:lts

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  restore-nodejs:
    description: "Restore Node.js dependencies"
    parameters:
      key:
        type: string
      working_directory:
        type: string
        default: *workspace_root
      default_branch:
        type: string
        default: master
    steps:
      - restore_cache:
          name: Restore node_modules cache
          keys:
            - << parameters.key >>-nodejs-{{ .Branch }}-{{ checksum "<< parameters.working_directory >>/yarn.lock" }}
            - << parameters.key >>-nodejs-<< parameters.default_branch >>-{{ checksum "<< parameters.working_directory >>/yarn.lock" }}
            - << parameters.key >>-nodejs-<< parameters.default_branch >>-

  install-nodejs:
    description: "Install Node.js dependencies"
    parameters:
      key:
        type: string
      working_directory:
        type: string
        default: *workspace_root
    steps:
      - restore-nodejs:
          key: << parameters.key >>
          working_directory: << parameters.working_directory >>

      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile && yarn lerna bootstrap --ci
          working_directory: << parameters.working_directory >>

      - save_cache:
          name: Save node_modules cache
          key: << parameters.key >>-nodejs-{{ .Branch }}-{{ checksum "<< parameters.working_directory >>/yarn.lock" }}
          paths:
            - << parameters.working_directory >>/node_modules

jobs:
  checkout:
    <<: *nodejs_container
    steps:
      - checkout

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./

  install:
    <<: *nodejs_container
    steps:
      - *attach_workspace

      - install-nodejs:
          key: v1-selling-partner-api-sdk-tmp

  test:
    <<: *test_container
    steps:
      - *attach_workspace

      - restore-nodejs:
          key: v1-selling-partner-api-sdk-tmp

      - run:
          name: Run tests
          command: yarn test --runInBand --ci --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/tests/

      - store_test_results:
          path: packages/api/reports/tests/

  lint-packages:
    <<: *nodejs_container
    steps:
      - *attach_workspace

      - restore-nodejs:
          key: v1-selling-partner-api-sdk-tmp

      - run:
          name: Run linter for packages
          command: yarn xo packages
          
workflows:
  version: 2

  push:
    jobs:
      - checkout

      - install:
          requires:
            - checkout
      
      - lint-packages:
          requires:
            - install

      - test:
          requires:
            - install
