/* tslint:disable */
/* eslint-disable */
/**
 * Listings Items v2021-08-01
 * The Selling Partner API for Listings Items (Listings Items API) provides programmatic access to selling partner listings on Amazon. Use this API in collaboration with the Selling Partner API for Product Type Definitions, which you use to retrieve the information about Amazon product types needed to use the Listings Items API.  For more information, see the [Listings Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2021-08-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FulfillmentAvailability } from './fulfillment-availability';
// May contain unused imports in some cases
// @ts-ignore
import type { Issue } from './issue';
// May contain unused imports in some cases
// @ts-ignore
import type { ItemOfferByMarketplace } from './item-offer-by-marketplace';
// May contain unused imports in some cases
// @ts-ignore
import type { ItemProcurement } from './item-procurement';
// May contain unused imports in some cases
// @ts-ignore
import type { ItemSummaryByMarketplace } from './item-summary-by-marketplace';

/**
 * A listings item.
 * @export
 * @interface Item
 */
export interface Item {
    /**
     * A selling partner provided identifier for an Amazon listing.
     * @type {string}
     * @memberof Item
     */
    'sku': string;
    /**
     * Summary details of a listings item.
     * @type {Array<ItemSummaryByMarketplace>}
     * @memberof Item
     */
    'summaries'?: Array<ItemSummaryByMarketplace>;
    /**
     * A JSON object containing structured listings item attribute data keyed by attribute name.
     * @type {{ [key: string]: any; }}
     * @memberof Item
     */
    'attributes'?: { [key: string]: any; };
    /**
     * The issues associated with the listings item.
     * @type {Array<Issue>}
     * @memberof Item
     */
    'issues'?: Array<Issue>;
    /**
     * Offer details for the listings item.
     * @type {Array<ItemOfferByMarketplace>}
     * @memberof Item
     */
    'offers'?: Array<ItemOfferByMarketplace>;
    /**
     * The fulfillment availability for the listings item.
     * @type {Array<FulfillmentAvailability>}
     * @memberof Item
     */
    'fulfillmentAvailability'?: Array<FulfillmentAvailability>;
    /**
     * The vendor procurement information for the listings item.
     * @type {Array<ItemProcurement>}
     * @memberof Item
     */
    'procurement'?: Array<ItemProcurement>;
}

