/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Finances
 * The Selling Partner API for Finances provides financial information that is relevant to a seller\'s business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range. 
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';

/**
 * Failed ad hoc disbursement event list.
 * @export
 * @interface FailedAdhocDisbursementEvent
 */
export interface FailedAdhocDisbursementEvent {
    /**
     * The type of fund transfer. For example, `Refund`.
     * @type {string}
     * @memberof FailedAdhocDisbursementEvent
     */
    'FundsTransfersType'?: string;
    /**
     * The transfer identifier.
     * @type {string}
     * @memberof FailedAdhocDisbursementEvent
     */
    'TransferId'?: string;
    /**
     * The disbursement identifier.
     * @type {string}
     * @memberof FailedAdhocDisbursementEvent
     */
    'DisbursementId'?: string;
    /**
     * The type of payment for disbursement. For example, `CREDIT_CARD`.
     * @type {string}
     * @memberof FailedAdhocDisbursementEvent
     */
    'PaymentDisbursementType'?: string;
    /**
     * The status of the failed `AdhocDisbursement`. For example, `HARD_DECLINED`.
     * @type {string}
     * @memberof FailedAdhocDisbursementEvent
     */
    'Status'?: string;
    /**
     * 
     * @type {Currency}
     * @memberof FailedAdhocDisbursementEvent
     */
    'TransferAmount'?: Currency;
    /**
     * A date in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format.
     * @type {string}
     * @memberof FailedAdhocDisbursementEvent
     */
    'PostedDate'?: string;
}

