/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Finances
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller\'s business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChargeComponent } from './charge-component';
// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import type { FeeComponent } from './fee-component';
// May contain unused imports in some cases
// @ts-ignore
import type { TaxWithheldComponent } from './tax-withheld-component';

/**
 * An event related to a rental transaction.
 * @export
 * @interface RentalTransactionEvent
 */
export interface RentalTransactionEvent {
    /**
     * An Amazon-defined identifier for an order.
     * @type {string}
     * @memberof RentalTransactionEvent
     */
    'AmazonOrderId'?: string;
    /**
     * The type of rental event.  Possible values:  * RentalCustomerPayment-Buyout - Transaction type that represents when the customer wants to buy out a rented item.  * RentalCustomerPayment-Extension - Transaction type that represents when the customer wants to extend the rental period.  * RentalCustomerRefund-Buyout - Transaction type that represents when the customer requests a refund for the buyout of the rented item.  * RentalCustomerRefund-Extension - Transaction type that represents when the customer requests a refund over the extension on the rented item.  * RentalHandlingFee - Transaction type that represents the fee that Amazon charges sellers who rent through Amazon.  * RentalChargeFailureReimbursement - Transaction type that represents when Amazon sends money to the seller to compensate for a failed charge.  * RentalLostItemReimbursement - Transaction type that represents when Amazon sends money to the seller to compensate for a lost item.
     * @type {string}
     * @memberof RentalTransactionEvent
     */
    'RentalEventType'?: string;
    /**
     * The number of days that the buyer extended an already rented item. This value is only returned for RentalCustomerPayment-Extension and RentalCustomerRefund-Extension events.
     * @type {number}
     * @memberof RentalTransactionEvent
     */
    'ExtensionLength'?: number;
    /**
     * Fields with a schema type of date are in ISO 8601 date time format (for example GroupBeginDate).
     * @type {string}
     * @memberof RentalTransactionEvent
     */
    'PostedDate'?: string;
    /**
     * A list of charge information on the seller\'s account.
     * @type {Array<ChargeComponent>}
     * @memberof RentalTransactionEvent
     */
    'RentalChargeList'?: Array<ChargeComponent>;
    /**
     * A list of fee component information.
     * @type {Array<FeeComponent>}
     * @memberof RentalTransactionEvent
     */
    'RentalFeeList'?: Array<FeeComponent>;
    /**
     * The name of the marketplace.
     * @type {string}
     * @memberof RentalTransactionEvent
     */
    'MarketplaceName'?: string;
    /**
     * 
     * @type {Currency}
     * @memberof RentalTransactionEvent
     */
    'RentalInitialValue'?: Currency;
    /**
     * 
     * @type {Currency}
     * @memberof RentalTransactionEvent
     */
    'RentalReimbursement'?: Currency;
    /**
     * A list of information about taxes withheld.
     * @type {Array<TaxWithheldComponent>}
     * @memberof RentalTransactionEvent
     */
    'RentalTaxWithheldList'?: Array<TaxWithheldComponent>;
}

