/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Finances
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller\'s business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';

/**
 * An event related to a value added service charge.
 * @export
 * @interface ValueAddedServiceChargeEvent
 */
export interface ValueAddedServiceChargeEvent {
    /**
     * Indicates the type of transaction.  Example: \'Other Support Service fees\'
     * @type {string}
     * @memberof ValueAddedServiceChargeEvent
     */
    'TransactionType'?: string;
    /**
     * 
     * @type {string}
     * @memberof ValueAddedServiceChargeEvent
     */
    'PostedDate'?: string;
    /**
     * A short description of the service charge event.
     * @type {string}
     * @memberof ValueAddedServiceChargeEvent
     */
    'Description'?: string;
    /**
     * 
     * @type {Currency}
     * @memberof ValueAddedServiceChargeEvent
     */
    'TransactionAmount'?: Currency;
}

