/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Shipping
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TrackingInformation } from './tracking-information';

/**
 * The response schema for the getTrackingInformation operation.
 * @export
 * @interface GetTrackingInformationResponse
 */
export interface GetTrackingInformationResponse {
    /**
     * 
     * @type {TrackingInformation}
     * @memberof GetTrackingInformationResponse
     */
    payload?: TrackingInformation;
    /**
     * A list of error responses returned when a request is unsuccessful.
     * @type {Array<Error>}
     * @memberof GetTrackingInformationResponse
     */
    errors?: Array<Error>;
}


