/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Shipping
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Currency } from './currency';
import { ServiceType } from './service-type';
import { ShippingPromiseSet } from './shipping-promise-set';
import { Weight } from './weight';

/**
 * The specific rate for a shipping service, or null if no service available.
 * @export
 * @interface ServiceRate
 */
export interface ServiceRate {
    /**
     * 
     * @type {Currency}
     * @memberof ServiceRate
     */
    totalCharge: Currency;
    /**
     * 
     * @type {Weight}
     * @memberof ServiceRate
     */
    billableWeight: Weight;
    /**
     * 
     * @type {ServiceType}
     * @memberof ServiceRate
     */
    serviceType: ServiceType;
    /**
     * 
     * @type {ShippingPromiseSet}
     * @memberof ServiceRate
     */
    promise: ShippingPromiseSet;
}


