/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Shipping
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The weight.
 * @export
 * @interface Weight
 */
export interface Weight {
    /**
     * The unit of measurement.
     * @type {string}
     * @memberof Weight
     */
    'unit': WeightUnitEnum;
    /**
     * The measurement value.
     * @type {number}
     * @memberof Weight
     */
    'value': number;
}

export const WeightUnitEnum = {
    G: 'g',
    Kg: 'kg',
    Oz: 'oz',
    Lb: 'lb'
} as const;

export type WeightUnitEnum = typeof WeightUnitEnum[keyof typeof WeightUnitEnum];


