/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Reports
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * The version of the OpenAPI document: 2020-09-04
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Encryption details required for decryption of a report document\'s contents.
 * @export
 * @interface ReportDocumentEncryptionDetails
 */
export interface ReportDocumentEncryptionDetails {
    /**
     * The encryption standard required to decrypt the document contents.
     * @type {string}
     * @memberof ReportDocumentEncryptionDetails
     */
    'standard': ReportDocumentEncryptionDetailsStandardEnum;
    /**
     * The vector to decrypt the document contents using Cipher Block Chaining (CBC).
     * @type {string}
     * @memberof ReportDocumentEncryptionDetails
     */
    'initializationVector': string;
    /**
     * The encryption key used to decrypt the document contents.
     * @type {string}
     * @memberof ReportDocumentEncryptionDetails
     */
    'key': string;
}

export const ReportDocumentEncryptionDetailsStandardEnum = {
    Aes: 'AES'
} as const;

export type ReportDocumentEncryptionDetailsStandardEnum = typeof ReportDocumentEncryptionDetailsStandardEnum[keyof typeof ReportDocumentEncryptionDetailsStandardEnum];


