/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for A+ Content Management
 * With the A+ Content API, you can build applications that help selling partners add rich marketing content to their Amazon product detail pages. A+ Content helps selling partners share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners assemble content by choosing from content modules and adding images and text.
 *
 * The version of the OpenAPI document: 2020-11-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Description } from './description.js';
// May contain unused imports in some cases
// @ts-ignore
import type { Issue } from './issue.js';
// May contain unused imports in some cases
// @ts-ignore
import type { MediaAllOf } from './media-all-of.js';
// May contain unused imports in some cases
// @ts-ignore
import type { MediaInfo } from './media-info.js';
// May contain unused imports in some cases
// @ts-ignore
import type { MediaStatus } from './media-status.js';
// May contain unused imports in some cases
// @ts-ignore
import type { MediaType } from './media-type.js';
// May contain unused imports in some cases
// @ts-ignore
import type { RelatedMedia } from './related-media.js';

/**
 * @type Media
 * A media entity with its related media associations. This is the unified shape used across all media operations.
 */
export type Media = MediaAllOf & MediaInfo;


