/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for Invoices.
 * Use the Selling Partner API for Invoices to retrieve and manage invoice-related operations, which can help selling partners manage their bookkeeping processes.
 *
 * The version of the OpenAPI document: 2024-06-19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * An object that contains the `documentId` and an S3 pre-signed URL that you can use to download the specified file.
 */
export interface InvoicesDocument {
    /**
     * The identifier of the export document.
     */
    'invoicesDocumentId'?: string;
    /**
     * A pre-signed URL that you can use to download the invoices document in zip format. This URL expires after 30 seconds.
     */
    'invoicesDocumentUrl'?: string;
}

