/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for Amazon Seller Wallet Open Banking API
 * This is a Amazon open banking api specification based on the Swagger 2.0 standard. It specifies all the api\'s that the third party will have to connect to in order to receive information from Amazon related to their customer\'s financial data.  _Please note the authentication & authorization api\'s are not part of this section and would be created & shared separately_  Some useful links: - [The SP-API repository](https://swagger-editor.dovydenk.people.a2z.com/) - [The source API definition for the Amazon Seller Wallet Open Banking API](https://swagger-editor.dovydenk.people.a2z.com/)
 *
 * The version of the OpenAPI document: 2024-03-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import type { FeeType } from './fee-type';

/**
 * Details of the fee.
 * @export
 * @interface Fee
 */
export interface Fee {
    /**
     * The unique identifier assigned to the fee.
     * @type {string}
     * @memberof Fee
     */
    'feeId': string;
    /**
     * 
     * @type {FeeType}
     * @memberof Fee
     */
    'feeType': FeeType;
    /**
     * A decimal number, such as an amount or FX rate.
     * @type {number}
     * @memberof Fee
     */
    'feeRateValue': number;
    /**
     * 
     * @type {Currency}
     * @memberof Fee
     */
    'feeAmount': Currency;
}



