/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for Amazon Seller Wallet Open Banking API Spec.  For more information, refer to the [Seller Wallet Open Banking API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/seller-wallet-open-banking-api-v2024-03-01-use-case-guide).
 * The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller\'s Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.
 *
 * The version of the OpenAPI document: 2024-03-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PaymentPreference } from './payment-preference';
// May contain unused imports in some cases
// @ts-ignore
import type { TransactionInstrumentDetails } from './transaction-instrument-details';
// May contain unused imports in some cases
// @ts-ignore
import type { TransactionType } from './transaction-type';
// May contain unused imports in some cases
// @ts-ignore
import type { TransferScheduleInformation } from './transfer-schedule-information';
// May contain unused imports in some cases
// @ts-ignore
import type { TransferScheduleStatus } from './transfer-schedule-status';

/**
 * Request body to initiate a scheduled transfer from a SW bank account to another customer defined bank account 
 */
export interface TransferScheduleRequest {
    /**
     * The unique identifier of the source Amazon SW bank account from where the money needs to be debited 
     */
    'sourceAccountId': string;
    /**
     * Represents 3 letter currency code in ISO 4217 standard format of the source payment method country 
     */
    'sourceCurrencyCode': string;
    /**
     * Optional field to specify the unique identifier of the destination bank account where the money needs to be deposited 
     */
    'destinationAccountId': string;
    'destinationTransactionInstrument': TransactionInstrumentDetails;
    'transactionType': TransactionType;
    'transferScheduleInformation': TransferScheduleInformation;
    'paymentPreference': PaymentPreference;
    'transferScheduleStatus'?: TransferScheduleStatus;
}



