/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for Amazon Seller Wallet Open Banking API Spec.  For more information, refer to the [Seller Wallet Open Banking API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/seller-wallet-open-banking-api-v2024-03-01-use-case-guide).
 * The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller\'s Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.
 *
 * The version of the OpenAPI document: 2024-03-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents current status of the transaction.
 */

export const TransactionStatus = {
    Expired: 'EXPIRED',
    Failed: 'FAILED',
    FailedCreditsApplied: 'FAILED_CREDITS_APPLIED',
    InProgress: 'IN_PROGRESS',
    PendingUserApproval: 'PENDING_USER_APPROVAL',
    Successful: 'SUCCESSFUL'
} as const;

export type TransactionStatus = typeof TransactionStatus[keyof typeof TransactionStatus];



