/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for Finances
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller\'s business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.
 *
 * The version of the OpenAPI document: 2024-06-19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Related business identifier of the transaction.
 */
export interface RelatedIdentifier {
    /**
     * Enumerated set of related business identifier names.
     */
    'relatedIdentifierName'?: RelatedIdentifierRelatedIdentifierNameEnum;
    /**
     * Corresponding value of RelatedIdentifierName
     */
    'relatedIdentifierValue'?: string;
}

export const RelatedIdentifierRelatedIdentifierNameEnum = {
    OrderId: 'ORDER_ID',
    ShipmentId: 'SHIPMENT_ID',
    FinancialEventGroupId: 'FINANCIAL_EVENT_GROUP_ID',
    RefundId: 'REFUND_ID',
    InvoiceId: 'INVOICE_ID',
    DisbursementId: 'DISBURSEMENT_ID',
    TransferId: 'TRANSFER_ID',
    DeferredTransactionId: 'DEFERRED_TRANSACTION_ID',
    ReleaseTransactionId: 'RELEASE_TRANSACTION_ID',
    SettlementId: 'SETTLEMENT_ID'
} as const;

export type RelatedIdentifierRelatedIdentifierNameEnum = typeof RelatedIdentifierRelatedIdentifierNameEnum[keyof typeof RelatedIdentifierRelatedIdentifierNameEnum];


