/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Merchant Fulfillment
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CurrencyAmount } from './currency-amount';
// May contain unused imports in some cases
// @ts-ignore
import { DeliveryExperienceOption } from './delivery-experience-option';

/**
 * The available delivery confirmation options, and the fee charged, if any.
 * @export
 * @interface AvailableDeliveryExperienceOption
 */
export interface AvailableDeliveryExperienceOption {
    /**
     * 
     * @type {DeliveryExperienceOption}
     * @memberof AvailableDeliveryExperienceOption
     */
    'DeliveryExperienceOption': DeliveryExperienceOption;
    /**
     * 
     * @type {CurrencyAmount}
     * @memberof AvailableDeliveryExperienceOption
     */
    'Charge': CurrencyAmount;
}



