/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Merchant Fulfillment
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Address } from './address';

/**
 * Request schema.
 * @export
 * @interface GetAdditionalSellerInputsRequest
 */
export interface GetAdditionalSellerInputsRequest {
    /**
     * An Amazon-defined shipping service identifier.
     * @type {string}
     * @memberof GetAdditionalSellerInputsRequest
     */
    'ShippingServiceId': string;
    /**
     * 
     * @type {Address}
     * @memberof GetAdditionalSellerInputsRequest
     */
    'ShipFromAddress': Address;
    /**
     * An Amazon-defined order identifier, in 3-7-7 format.
     * @type {string}
     * @memberof GetAdditionalSellerInputsRequest
     */
    'OrderId': string;
}

