/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Reports
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * The version of the OpenAPI document: 2021-06-30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReportDocument
 */
export interface ReportDocument {
    /**
     * The identifier for the report document. This identifier is unique only in combination with a seller ID.
     * @type {string}
     * @memberof ReportDocument
     */
    reportDocumentId: string;
    /**
     * A presigned URL for the report document. This URL expires after 5 minutes.
     * @type {string}
     * @memberof ReportDocument
     */
    url: string;
    /**
     * If present, the report document contents have been compressed with the provided algorithm.
     * @type {string}
     * @memberof ReportDocument
     */
    compressionAlgorithm?: ReportDocumentCompressionAlgorithmEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ReportDocumentCompressionAlgorithmEnum {
    Gzip = 'GZIP'
}



