/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Retail Procurement Shipments
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Location } from './location';

/**
 * Contractual or operational port or point relevant to the movement of the cargo.
 */
export interface Stop {
    /**
     * Provide the function code.
     */
    'functionCode': StopFunctionCodeEnum;
    'locationIdentification'?: Location;
    /**
     * Date and time of the arrival of the cargo.
     */
    'arrivalTime'?: string;
    /**
     * Date and time of the departure of the cargo.
     */
    'departureTime'?: string;
}

export const StopFunctionCodeEnum = {
    PortOfDischarge: 'PortOfDischarge',
    FreightPayableAt: 'FreightPayableAt',
    PortOfLoading: 'PortOfLoading'
} as const;

export type StopFunctionCodeEnum = typeof StopFunctionCodeEnum[keyof typeof StopFunctionCodeEnum];


