/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for Amazon Warehousing and Distribution
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory. 
 *
 * The version of the OpenAPI document: 2024-05-09
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LabelOwner } from './label-owner';
// May contain unused imports in some cases
// @ts-ignore
import type { PrepInstruction } from './prep-instruction';
// May contain unused imports in some cases
// @ts-ignore
import type { PrepOwner } from './prep-owner';

/**
 * The preparation details for a product. This contains the prep category, prep owner, and label owner. Prep instructions are generated based on the specified category.
 * @export
 * @interface PrepDetails
 */
export interface PrepDetails {
    /**
     * 
     * @type {LabelOwner}
     * @memberof PrepDetails
     */
    'labelOwner'?: LabelOwner;
    /**
     * The preparation category for shipping an item to Amazon\'s fulfillment network.
     * @type {string}
     * @memberof PrepDetails
     */
    'prepCategory'?: string;
    /**
     * Information that pertains to the preparation of inbound products. This is generated based on the specified category.
     * @type {Array<PrepInstruction>}
     * @memberof PrepDetails
     */
    'prepInstructions'?: Array<PrepInstruction>;
    /**
     * 
     * @type {PrepOwner}
     * @memberof PrepDetails
     */
    'prepOwner'?: PrepOwner;
}



