/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for AWD
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD).
 *
 * The version of the OpenAPI document: 2024-05-09
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Unit of measurement for the package weight.
 * @export
 * @enum {string}
 */

export const WeightUnitOfMeasurement = {
    Pounds: 'POUNDS',
    Kilograms: 'KILOGRAMS'
} as const;

export type WeightUnitOfMeasurement = typeof WeightUnitOfMeasurement[keyof typeof WeightUnitOfMeasurement];



