/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for External Fulfillment Inventory Management
 * You can use the Amazon External Fulfillment Inventory API to manage inventory operations in Amazon\'s External Fulfillment network, including batch inventory updates and retrievals.
 *
 * The version of the OpenAPI document: 2024-09-11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HttpStatusLine } from './http-status-line';
// May contain unused imports in some cases
// @ts-ignore
import type { InventoryResponseBody } from './inventory-response-body';

/**
 * A response to an individual inventory request.
 */
export interface InventoryResponse {
    'status': HttpStatusLine;
    'body': InventoryResponseBody;
}

