/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for Amazon External Fulfillment Location Management
 * You can use the External Fulfillment Location API to manage locations in the sandbox environment for end-to-end testing. This API is available only in the sandbox environment.
 *
 * The version of the OpenAPI document: 2026-07-30
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/external-fulfillment-location-api.js';

