/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for FBA inbound operations.
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon\'s fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * The version of the OpenAPI document: 2024-03-20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Incentive } from './incentive';

/**
 * Contains information pertaining to the placement of the contents of an inbound plan and the related costs.
 * @export
 * @interface PlacementOption
 */
export interface PlacementOption {
    /**
     * Discount for the offered option.
     * @type {Array<Incentive>}
     * @memberof PlacementOption
     */
    'discounts': Array<Incentive>;
    /**
     * The expiration date of the placement option. This is in ISO 8601 datetime format with pattern `yyyy-MM-ddTHH:mm:ss.sssZ`.
     * @type {string}
     * @memberof PlacementOption
     */
    'expiration'?: string;
    /**
     * Fee for the offered option.
     * @type {Array<Incentive>}
     * @memberof PlacementOption
     */
    'fees': Array<Incentive>;
    /**
     * Identifier to a placement option. A placement option represents the shipment splits and destinations of SKUs.
     * @type {string}
     * @memberof PlacementOption
     */
    'placementOptionId': string;
    /**
     * Shipment ids.
     * @type {Array<string>}
     * @memberof PlacementOption
     */
    'shipmentIds': Array<string>;
    /**
     * The status of a placement option. Can be `OFFERED`, `ACCEPTED`, or `EXPIRED`.
     * @type {string}
     * @memberof PlacementOption
     */
    'status': string;
}

