/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for FBA inbound operations.
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon\'s fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * The version of the OpenAPI document: 2024-03-20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Representation of a location used within the inbounding experience.
 * @export
 * @interface Region
 */
export interface Region {
    /**
     * ISO 3166 standard alpha-2 country code.
     * @type {string}
     * @memberof Region
     */
    'countryCode'?: string;
    /**
     * State.
     * @type {string}
     * @memberof Region
     */
    'state'?: string;
    /**
     * An identifier for a warehouse, such as a FC, IXD, upstream storage.
     * @type {string}
     * @memberof Region
     */
    'warehouseId'?: string;
}

