/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Catalog Items
 * The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ShippingTimeType } from './shipping-time-type';

/**
 * 
 * @export
 * @interface QualifiersType
 */
export interface QualifiersType {
    /**
     * The condition of the item. Possible values: New, Used, Collectible, Refurbished, or Club.
     * @type {string}
     * @memberof QualifiersType
     */
    ItemCondition: string;
    /**
     * The item subcondition for the offer listing. Possible values: New, Mint, Very Good, Good, Acceptable, Poor, Club, OEM, Warranty, Refurbished Warranty, Refurbished, Open Box, or Other.
     * @type {string}
     * @memberof QualifiersType
     */
    ItemSubcondition: string;
    /**
     * The fulfillment channel for the item. Possible values:  * Amazon - Fulfilled by Amazon. * Merchant - Fulfilled by the seller.
     * @type {string}
     * @memberof QualifiersType
     */
    FulfillmentChannel: string;
    /**
     * Indicates whether the marketplace specified in the request and the location that the item ships from are in the same country. Possible values: True, False, or Unknown.
     * @type {string}
     * @memberof QualifiersType
     */
    ShipsDomestically: string;
    /**
     * 
     * @type {ShippingTimeType}
     * @memberof QualifiersType
     */
    ShippingTime: ShippingTimeType;
    /**
     * (98-100%, 95-97%, 90-94%, 80-89%, 70-79%, Less than 70%, or Just launched ) – Indicates the percentage of feedback ratings that were positive over the past 12 months.
     * @type {string}
     * @memberof QualifiersType
     */
    SellerPositiveFeedbackRating: string;
}


