/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Direct Fulfillment Shipping
 * Use the Selling Partner API for Direct Fulfillment Shipping to access a direct fulfillment vendor\'s shipping data.
 *
 * The version of the OpenAPI document: 2021-12-28
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Address } from './address';
// May contain unused imports in some cases
// @ts-ignore
import type { TaxRegistrationDetails } from './tax-registration-details';

/**
 * The name, address, and tax details of a party.
 * @export
 * @interface PartyIdentification
 */
export interface PartyIdentification {
    /**
     * The identifier of the party.
     * @type {string}
     * @memberof PartyIdentification
     */
    'partyId': string;
    /**
     * 
     * @type {Address}
     * @memberof PartyIdentification
     */
    'address'?: Address;
    /**
     * The tax registration details of the party.
     * @type {Array<TaxRegistrationDetails>}
     * @memberof PartyIdentification
     */
    'taxRegistrationDetails'?: Array<TaxRegistrationDetails>;
}

