/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Services
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The input appointment time details.
 */
export interface AppointmentTimeInput {
    /**
     * The date, time in UTC for the start time of an appointment in ISO 8601 format.
     */
    'startTime': string;
    /**
     * The duration of an appointment in minutes.
     */
    'durationInMinutes'?: number;
}

