/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Services
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Document that captured during service appointment fulfillment that portrays proof of completion
 * @export
 * @interface FulfillmentDocument
 */
export interface FulfillmentDocument {
    /**
     * The identifier of the upload destination. Get this value by calling the `createServiceDocumentUploadDestination` operation of the Services API.
     * @type {string}
     * @memberof FulfillmentDocument
     */
    'uploadDestinationId'?: string;
    /**
     * Sha256 hash of the file content. This value is used to determine if the file has been corrupted or tampered with during transit.
     * @type {string}
     * @memberof FulfillmentDocument
     */
    'contentSha256'?: string;
}

