/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Services
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DayOfWeek } from './day-of-week';

/**
 * Repeated occurrence of an event in a time range.
 * @export
 * @interface Recurrence
 */
export interface Recurrence {
    /**
     * End time of the recurrence.
     * @type {string}
     * @memberof Recurrence
     */
    'endTime': string;
    /**
     * Days of the week when recurrence is valid. If the schedule is valid every Monday, input will only contain `MONDAY` in the list.
     * @type {Array<DayOfWeek>}
     * @memberof Recurrence
     */
    'daysOfWeek'?: Array<DayOfWeek>;
    /**
     * Days of the month when recurrence is valid.
     * @type {Array<number>}
     * @memberof Recurrence
     */
    'daysOfMonth'?: Array<number>;
}

