/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Services
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The scope of work for the order.
 */
export interface ScopeOfWork {
    /**
     * The Amazon Standard Identification Number (ASIN) of the service job.
     */
    'asin'?: string;
    /**
     * The title of the service job.
     */
    'title'?: string;
    /**
     * The number of service jobs.
     */
    'quantity'?: number;
    /**
     * A list of skills required to perform the job.
     */
    'requiredSkills'?: Array<string>;
}

