/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for Finance Remittance
 * The Selling Partner API for Finance Remittance provides programmatic access to selling partner payment remittance data, including remittance summaries and detailed line items.
 *
 * The version of the OpenAPI document: 2026-03-17
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RemittanceHeader } from './remittance-header.js';

/**
 * The response for the `getRemittanceHeaders` operation.
 */
export interface GetRemittancesResponse {
    /**
     * A list of remittance summaries.
     */
    'remittances'?: Array<RemittanceHeader>;
    /**
     * A token to fetch the next page of results. Present when more results are available.
     */
    'nextToken'?: string;
    /**
     * The total number of records across all pages.
     */
    'numOfRecords'?: number;
}

