/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for Finance Remittance
 * The Selling Partner API for Finance Remittance provides programmatic access to selling partner payment remittance data, including remittance summaries and detailed line items.
 *
 * The version of the OpenAPI document: 2026-03-17
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency.js';
// May contain unused imports in some cases
// @ts-ignore
import type { RelatedIdentifier } from './related-identifier.js';
// May contain unused imports in some cases
// @ts-ignore
import type { RemittanceStatus } from './remittance-status.js';

/**
 * Summary information for a remittance payment.
 */
export interface RemittanceHeader {
    /**
     * The date of the payment in ISO 8601 date-time format.
     */
    'paymentDate': string;
    /**
     * The external payment reference number associated with the remittance. Vendors can use this identifier to search for payment information.
     */
    'paymentNumber'?: string;
    /**
     * The unique internal identifier for the payment record in the remittance system.
     */
    'uniquePaymentId': string;
    /**
     * Fields with a schema type of `BigDecimal` are a signed decimal number (for example `currencyAmount`).
     */
    'exchangeRate'?: number;
    'paymentAmount': Currency;
    'paymentAmountInInvoiceCurrency'?: Currency;
    /**
     * The method used for the payment.
     */
    'paymentMethod'?: string;
    'remittanceStatus': RemittanceStatus;
    /**
     * The number of line items in the remittance.
     */
    'lineItemCount'?: number;
    /**
     * A list of related business identifiers for the remittance.
     */
    'relatedIdentifiers'?: Array<RelatedIdentifier>;
    /**
     * The country code associated with the remittance in ISO 3166-1 alpha-2 format.
     */
    'countryCode'?: string;
}



