/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for FBA Inventory
 * The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon\'s fulfillment network.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The quantity of unfulfillable inventory.
 */
export interface UnfulfillableQuantity {
    /**
     * The total number of units in Amazon\'s fulfillment network in unsellable condition.
     */
    'totalUnfulfillableQuantity'?: number;
    /**
     * The number of units in customer damaged disposition.
     */
    'customerDamagedQuantity'?: number;
    /**
     * The number of units in warehouse damaged disposition.
     */
    'warehouseDamagedQuantity'?: number;
    /**
     * The number of units in distributor damaged disposition.
     */
    'distributorDamagedQuantity'?: number;
    /**
     * The number of units in carrier damaged disposition.
     */
    'carrierDamagedQuantity'?: number;
    /**
     * The number of units in defective disposition.
     */
    'defectiveQuantity'?: number;
    /**
     * The number of units in expired disposition.
     */
    'expiredQuantity'?: number;
}

