/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for Promotions
 * The Selling Partner API for Promotions enables selling partners to create and manage promotions.
 *
 * The version of the OpenAPI document: 2025-12-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Issue information with code, message, and severity.
 */
export interface Issue {
    /**
     * Issue code identifier.
     */
    'code': string;
    /**
     * Issue description.
     */
    'message': string;
    /**
     * Issue severity level.
     */
    'severity': IssueSeverityEnum;
}

export const IssueSeverityEnum = {
    Error: 'ERROR',
    Warning: 'WARNING',
} as const;

export type IssueSeverityEnum = typeof IssueSeverityEnum[keyof typeof IssueSeverityEnum];


