/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for Promotions
 * The Selling Partner API for Promotions enables selling partners to create and manage promotions.
 *
 * The version of the OpenAPI document: 2025-12-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Budget } from './budget.js';
// May contain unused imports in some cases
// @ts-ignore
import type { CouponType } from './coupon-type.js';
// May contain unused imports in some cases
// @ts-ignore
import type { CustomerSegment } from './customer-segment.js';
// May contain unused imports in some cases
// @ts-ignore
import type { LatestRevisionAllOf } from './latest-revision-all-of.js';
// May contain unused imports in some cases
// @ts-ignore
import type { Merchandising } from './merchandising.js';
// May contain unused imports in some cases
// @ts-ignore
import type { PromotionBenefit } from './promotion-benefit.js';
// May contain unused imports in some cases
// @ts-ignore
import type { PromotionFeeSnapshot } from './promotion-fee-snapshot.js';
// May contain unused imports in some cases
// @ts-ignore
import type { PromotionIssue } from './promotion-issue.js';
// May contain unused imports in some cases
// @ts-ignore
import type { PromotionRevisionAttributes } from './promotion-revision-attributes.js';
// May contain unused imports in some cases
// @ts-ignore
import type { PromotionType } from './promotion-type.js';
// May contain unused imports in some cases
// @ts-ignore
import type { PurchaseRequirements } from './purchase-requirements.js';
// May contain unused imports in some cases
// @ts-ignore
import type { Schedule } from './schedule.js';
// May contain unused imports in some cases
// @ts-ignore
import type { Selection } from './selection.js';

/**
 * @type LatestRevision
 * The latest revision data, when it diverges from the published revision. Present only when an edit is still processing or was rejected. Mirrors the top-level promotion object structure.
 */
export type LatestRevision = LatestRevisionAllOf & PromotionRevisionAttributes;


