/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for Promotions
 * The Selling Partner API for Promotions enables selling partners to create and manage promotions.
 *
 * The version of the OpenAPI document: 2025-12-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AmountThreshold } from './amount-threshold.js';
// May contain unused imports in some cases
// @ts-ignore
import type { QuantityThreshold } from './quantity-threshold.js';

/**
 * Minimum purchase requirements using quantity-based or amount-based conditions for basket building promotions. You can specify conditions within purchase requirements and multi-tier benefit configurations. You must specify exactly one of `quantityThreshold` or `amountThreshold`.
 */
export interface PurchaseCondition {
    'quantityThreshold'?: QuantityThreshold;
    'amountThreshold'?: AmountThreshold;
}

