/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for Promotions
 * The Selling Partner API for Promotions enables selling partners to create and manage promotions.
 *
 * The version of the OpenAPI document: 2025-12-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency.js';
// May contain unused imports in some cases
// @ts-ignore
import type { FeeFrequency } from './fee-frequency.js';

/**
 * Upfront fee (or a flat fee) for each promotion submitted.
 */
export interface UpfrontFee {
    'rate': Currency;
    'frequency': FeeFrequency;
}



