/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for Amazon Warehousing and Distribution
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory. 
 *
 * The version of the OpenAPI document: 2024-05-09
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DistributionPackageContents } from './distribution-package-contents';
// May contain unused imports in some cases
// @ts-ignore
import type { DistributionPackageType } from './distribution-package-type';
// May contain unused imports in some cases
// @ts-ignore
import type { MeasurementData } from './measurement-data';

/**
 * Represents an AWD distribution package.
 */
export interface DistributionPackage {
    'contents': DistributionPackageContents;
    'measurements': MeasurementData;
    'type': DistributionPackageType;
}



