/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for Amazon Warehousing and Distribution
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory. 
 *
 * The version of the OpenAPI document: 2024-05-09
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProductAttribute } from './product-attribute';

/**
 * Represents a product with sku details and corresponding quantity
 */
export interface DistributionProduct {
    /**
     * Attributes for this instance of the product, i.e. already-prepped, or other attributes that distinguish the product beyond the SKU.
     */
    'attributes'?: Array<ProductAttribute>;
    /**
     * Quantity of the product
     */
    'quantity': number;
    /**
     * The seller/merchant stock keeping unit (SKU).
     */
    'sku': string;
}

