/* tslint:disable */
/* eslint-disable */
/**
 * The Selling Partner API for Amazon Warehousing and Distribution
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory. 
 *
 * The version of the OpenAPI document: 2024-05-09
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Label page type.
 */

export const PageType = {
    PlainPaper: 'PLAIN_PAPER',
    LetterPcpFulfillmentlabel: 'LETTER_PCP_FULFILLMENTLABEL',
    Letter2Horizontal: 'LETTER_2_HORIZONTAL',
    Letter2: 'LETTER_2',
    ThermalNoCarrierRotation: 'THERMAL_NO_CARRIER_ROTATION',
    Thermal: 'THERMAL',
    A4Paper: 'A4_PAPER',
    A42Horizontal: 'A4_2_HORIZONTAL',
    ThermalSquare10Cm: 'THERMAL_SQUARE_10CM',
} as const;

export type PageType = typeof PageType[keyof typeof PageType];



