/* tslint:disable */
/* eslint-disable */
/**
 * Selling Partner API for Tokens 
 * The Selling Partner API for Tokens provides a secure way to access a customers\'s PII (Personally Identifiable Information). You can call the Tokens API to get a Restricted Data Token (RDT) for one or more restricted resources that you specify. The RDT authorizes you to make subsequent requests to access these restricted resources.
 *
 * The version of the OpenAPI document: 2021-03-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Model of a restricted resource.
 * @export
 * @interface RestrictedResource
 */
export interface RestrictedResource {
    /**
     * The HTTP method used with the restricted resource.
     * @type {string}
     * @memberof RestrictedResource
     */
    method: RestrictedResourceMethodEnum;
    /**
     * The path from a restricted operation. This could be:  - A specific path containing a seller\'s order ID, for example ```/orders/v0/orders/902-3159896-1390916/address```.  - A generic path that does not contain a seller\'s order ID, for example```/orders/v0/orders/{orderId}/address```).
     * @type {string}
     * @memberof RestrictedResource
     */
    path: string;
}

/**
    * @export
    * @enum {string}
    */
export enum RestrictedResourceMethodEnum {
    Get = 'GET',
    Put = 'PUT',
    Post = 'POST',
    Delete = 'DELETE'
}



