/* tslint:disable */
/* eslint-disable */
/**
 * Amazon Shipping API
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 * Contact: swa-api-core@amazon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A set of measurements for a three-dimensional object.
 */
export interface Dimensions {
    /**
     * The length of the package.
     */
    'length': number;
    /**
     * The width of the package.
     */
    'width': number;
    /**
     * The height of the package.
     */
    'height': number;
    /**
     * The unit of measurement.
     */
    'unit': DimensionsUnitEnum;
}

export const DimensionsUnitEnum = {
    Inch: 'INCH',
    Centimeter: 'CENTIMETER'
} as const;

export type DimensionsUnitEnum = typeof DimensionsUnitEnum[keyof typeof DimensionsUnitEnum];


